NGO_PROFILES = {
    "health_large_international": "Health (Large International) - Focus on national health infrastructure, mass vaccination programs, epidemiological trends, and global funding allocation.",
    "health_medium_regional": "Health (Medium Regional) - Focus on building community clinics, regional disease prevention, and establishing maternal health programs across districts.",
    "health_small_niche_disability": "Health (Small Niche - Disability) - Focus on highly localized, specialized mobility therapies, wheelchair accessibility advocacy, and individual patient care.",
    "health_small_niche_mental": "Health (Small Niche - Mental Health) - Focus on local community counseling, trauma support groups, and suicide prevention initiatives.",
    "health_small_niche_nutrition": "Health (Small Niche - Nutrition) - Focus on school feeding programs, infant malnourishment interventions, and local food fortification.",
    "service_welfare_social": "Service & Welfare (Social Services) - Focus on crisis intervention, emergency housing, food security, and aged care.",
    "community_arts": "Community & Grassroots (Arts & Cultural) - Focus on community engagement, local heritage, theater, and Indigenous cultural preservation.",
    "community_sports": "Community & Grassroots (Recreation & Sports) - Focus on youth sports, community wellness, and social inclusion.",
    "development_education": "Development (Education & Training) - Focus on alternative schooling, adult literacy, and vocational training.",
    "development_economic": "Development (Economic Empowerment) - Focus on micro-finance, agricultural co-operatives, job creation, and social enterprises.",
    "environmental_conservation": "Environmental (Conservation) - Focus on local land care, wildlife rescue, rehabilitation, and marine habitat preservation.",
    "environmental_sustainability": "Environmental (Sustainability) - Focus on community renewable energy, recycling initiatives, and climate action advocacy.",
    "advocacy_human_rights": "Advocacy & Human Rights - Focus on civil liberties, gender equality, refugee support, and animal welfare.",
    "general": "General Non-Governmental Organization - Focus on overarching humanitarian impact and community support.",
}

DATASET_TOPICS = [
    "Agriculture and Forestry",
    "Climate Change, Disasters and Risks",
    "Economy",
    "Education",
    "Energy",
    "Environment",
    "Fisheries and Aquaculture",
    "Food",
    "Gender",
    "Health",
    "Information, Communication and Technology",
    "Ocean and Maritime",
    "Population",
    "Social and Culture",
]
